import { Project, Skill, Service } from './types';
import React from 'react';

export const SKILLS: Skill[] = [
  { name: 'VEO 3 (Flow)', category: 'AI', iconName: 'Sparkle', color: 'from-blue-400 to-purple-500' },
  { name: 'Kling AI', category: 'AI', iconName: 'Sparkle', color: 'from-purple-400 to-pink-500' },
  { name: 'RunwayML', category: 'AI', iconName: 'Sparkle', color: 'from-indigo-400 to-blue-500' },
  { name: 'Google Gemini', category: 'AI', iconName: 'Bot', color: 'from-green-400 to-emerald-600' },
  { name: 'DaVinci Resolve', category: 'Color', iconName: 'Aperture', color: 'from-pink-500 to-rose-600' },
  { name: 'Adobe Premiere Pro', category: 'Editing', iconName: 'Scissors', color: 'from-purple-600 to-indigo-600' },
];

export const SERVICES: Service[] = [
  {
    title: 'AI Video Production',
    description: 'Full service from script to final cut. Using VEO 3 and Kling AI, we create cinematic-quality commercials with consistent characters and settings.',
    iconName: 'Video',
  },
  {
    title: 'Advanced Prompt Engineering',
    description: 'Using ChatGPT, Google Gemini Nano Banana, and JSON formatting techniques, we create scene designs that go beyond standard prompts and provide full control.',
    iconName: 'Terminal',
  },
  {
    title: 'Post-Production & Color Grading',
    description: 'Editing, color grading, and finalizing raw footage generated by AI using Adobe Premiere Pro and DaVinci Resolve.',
    iconName: 'Sliders',
  },
  {
    title: 'Creative Copywriting & SEO',
    description: "SEO-optimized blog content, ad copy, and scriptwriting to strengthen your brand's digital presence.",
    iconName: 'Pen',
  },
];

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Neon Nights',
    client: 'CyberDrink',
    category: 'Commercial',
    thumbnailUrl: '/Media/Thumbnails/1.png',
    videoUrl: '/Media/Projects/1.mp4',
    aspectRatio: 'landscape',
    description: 'High-energy commercial spot featuring VFX and fast-paced editing.',
  },
  {
    id: '2',
    title: 'Urban Explorer',
    client: 'TravelCo',
    category: 'Social Media',
    thumbnailUrl: '/Media/Thumbnails/2.png',
    videoUrl: '/Media/Projects/2.mp4',
    aspectRatio: 'portrait',
    description: 'Vertical storytelling optimized for TikTok and Reels retention.',
  },
  {
    id: '3',
    title: 'Origins',
    client: 'History Channel',
    category: 'Documentary',
    thumbnailUrl: '/Media/Thumbnails/3.png',
    videoUrl: '/Media/Projects/3.mp4',
    aspectRatio: 'landscape',
    description: 'Color grading and sound design for a historical mini-doc.',
  },
  {
    id: '4',
    title: 'Fashion Week',
    client: 'Vogue',
    category: 'Social Media',
    thumbnailUrl: '/Media/Thumbnails/4.png',
    videoUrl: '/Media/Projects/4.mp4',
    aspectRatio: 'portrait',
    description: 'Fast turnaround event coverage with stylized edits.',
  },
  {
    id: '5',
    title: 'Summer Vibes',
    client: 'SodaPop',
    category: 'Commercial',
    thumbnailUrl: '/Media/Thumbnails/5.png',
    videoUrl: '/Media/Projects/5.mp4',
    aspectRatio: 'square',
    description: 'Social-first campaign designed for Instagram feed.',
  },
];

export const NAV_LINKS = [
  { label: 'Work', href: '#work' },
  { label: 'About', href: '#about' },
  { label: 'Services', href: '#services' },
  { label: 'Skills', href: '#skills' },
  { label: 'Contact', href: '#contact' },
];