import { Project, Skill, Service } from './types';
import React from 'react';

export const SKILLS: Skill[] = [
  { name: 'VEO 3 (Flow)', category: 'AI', iconName: 'Sparkle', color: 'from-blue-400 to-purple-500' },
  { name: 'Kling AI', category: 'AI', iconName: 'Sparkle', color: 'from-purple-400 to-pink-500' },
  { name: 'RunwayML', category: 'AI', iconName: 'Sparkle', color: 'from-indigo-400 to-blue-500' },
  { name: 'Google Gemini', category: 'AI', iconName: 'Bot', color: 'from-green-400 to-emerald-600' },
  { name: 'DaVinci Resolve', category: 'Color', iconName: 'Aperture', color: 'from-pink-500 to-rose-600' },
  { name: 'Adobe Premiere Pro', category: 'Editing', iconName: 'Scissors', color: 'from-purple-600 to-indigo-600' },
];

export const SERVICES: Service[] = [
  {
    title: 'AI Video Production',
    description: 'Full service from script to final cut. Using VEO 3 and Kling AI, we create cinematic-quality commercials with consistent characters and settings.',
    iconName: 'Video',
  },
  {
    title: 'Advanced Prompt Engineering',
    description: 'Using ChatGPT, Google Gemini Nano Banana, and JSON formatting techniques, we create scene designs that go beyond standard prompts and provide full control.',
    iconName: 'Terminal',
  },
  {
    title: 'Post-Production & Color Grading',
    description: 'Editing, color grading, and finalizing raw footage generated by AI using Adobe Premiere Pro and DaVinci Resolve.',
    iconName: 'Sliders',
  },
  {
    title: 'Creative Copywriting & SEO',
    description: "SEO-optimized blog content, ad copy, and scriptwriting to strengthen your brand's digital presence.",
    iconName: 'Pen',
  },
];

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'High-Fidelity Product Integration and Photorealistic Character Control',
    client: 'Cosmetics & Beauty · Clerie Mask',
    category: 'Commercial',
    // Cosmetics & Beauty (Clerie Mask)
    thumbnailUrl: '1.png',
    videoUrl: '1.mp4',
    aspectRatio: 'landscape',
    description:
      'The biggest challenge in AI advertising is creating a convincing human expression while preserving the typography on the product. In this work, I achieved the "flawless skin" texture required by the cosmetics industry while ensuring the finest text on the product packaging (Net weight, ingredients) was rendered without distortion. The lighting, texture, and brand identity are on par with a studio-quality production.',
  },
  {
    id: '2',
    title: 'AI-Powered Graphic Design and Typographic Arrangement',
    client: 'Food & Graphic Design · Pepper Paste',
    category: 'Commercial',
    // Food & Graphic Design (Pepper Paste)
    thumbnailUrl: '2.png',
    videoUrl: '2.mp4',
    aspectRatio: 'portrait',
    description:
      'We push the boundaries of AI not only in video but also in static visual advertising. In this project, specific text elements like "Organic" and "650gr," as well as logos, were rendered flawlessly. The appetizing realism of the product texture and graphic design elements (badges, icons) have been integrated into a single composition with print-ready quality.',
  },
  {
    id: '3',
    title: 'User Experience (UX) Focused Scenario Design',
    client: 'E-Commerce & UI/UX Integration · Mobile App',
    category: 'Commercial',
    // E-Commerce & UI/UX Integration (Mobile App)
    thumbnailUrl: '3.jpg',
    videoUrl: '3.mp4',
    aspectRatio: 'landscape',
    description:
      "Storytelling around a mobile application's usage is the heart of digital marketing. In this scene, a perfect balance was struck between the character's emotion and the clarity of the interface (UI) on the phone screen. Details such as product listings, prices, and 'Add to Cart' buttons were integrated into the visual/video with the sharpness of a real screenshot, avoiding AI hallucinations.",
  },
  {
    id: '4',
    title: 'Macro Texture Detail and Material Realism',
    client: 'Fashion & Outdoor · Blue Glove - Detail',
    category: 'Commercial',
    // Fashion & Outdoor (Blue Glove - Detail)
    thumbnailUrl: '4.png',
    videoUrl: '4.mp4',
    aspectRatio: 'portrait',
    description:
      "Conveying fabric technology is critical in outdoor clothing products. In this close-up shot, the glove's neoprene texture, stitching details, and the alignment of the brand logo with the fabric's folds were created with strict adherence to physical reality. The cold weather atmosphere is conveyed to the viewer through the color palette and depth of field.",
  },
  {
    id: '5',
    title: 'Fluid Dynamics and Product Functionality Demonstration',
    client: 'Performance Test & Physics Simulation · Waterproofing',
    category: 'Commercial',
    // Performance Test & Physics Simulation (Waterproofing)
    thumbnailUrl: '5.png',
    videoUrl: '5.mp4',
    aspectRatio: 'square',
    description:
      "Using 'Start/End Frame' techniques, the product from the previous visual was maintained in identical form to test its waterproof feature. The water flowing off the glove's surface, the behavior of the droplets, and the light refractions serve as a demonstration of AI flawlessly processing the laws of physics (fluid dynamics). Spatial and product consistency were achieved with complete success.",
  },
];

export const NAV_LINKS = [
  { label: 'Work', href: '#work' },
  { label: 'About', href: '#about' },
  { label: 'Services', href: '#services' },
  { label: 'Skills', href: '#skills' },
  { label: 'Contact', href: '#contact' },
];
